In [127]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [128]:
data = pd.read_csv('Inflation.csv')
X= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

In [129]:
print(X)

[['Sudan' 138.8 1]
 ['Zimbabwe' 104.7 2]
 ['Turkey' 72.3 3]
 ['Suriname' 52.4 4]
 ['Sri Lanka' 49.7 5]
 ['Haiti' 34.0 6]
 ['Ghana' 31.3 7]
 ['Moldova' 28.7 8]
 ['Sierra Leone' 27.2 9]
 ['Laos' 23.0 10]
 ['Malawi' 21.0 11]
 ['Ukraine' 20.2 12]
 ['Pakistan' 19.9 13]
 ['Lithuania' 19.7 14]
 ['Estonia' 19.4 15]
 ['Burundi' 18.8 16]
 ['Nigeria' 18.8 17]
 ['S.T.&Principe' 18.0 18]
 ['Rwanda' 17.7 19]
 ['Latvia' 17.3 20]
 ['Bulgaria' 15.3 21]
 ['Belarus' 15.2 22]
 ['Czechia' 15.1 23]
 ['Mongolia' 15.1 24]
 ['Hungary' 14.6 25]
 ['Poland' 14.4 26]
 ['Burkina Faso' 14.3 27]
 ['North Macedonia' 14.2 28]
 ['Bosnia & Herz.' 14.0 29]
 ['Azerbaijan' 13.9 30]
 ['Egypt' 13.9 31]
 ['Kyrgyzstan' 13.9 32]
 ['Romania' 13.8 33]
 ['Montenegro' 13.0 34]
 ['Slovakia' 12.8 35]
 ['Palau' 12.4 36]
 ['Serbia' 12.0 37]
 ['Georgia' 11.9 38]
 ['Botswana' 11.7 39]
 ['Chile' 11.6 40]
 ['Gambia' 11.5 41]
 ['Uzbekistan' 11.4 42]
 ['Samoa' 11.0 43]
 ['Tonga' 11.0 44]
 ['Zambia' 11.0 45]
 ['Croatia' 10.8 46]
 ['Mauritius' 

In [130]:
print(y)

['1960 - 2022' '2010 - 2022' '1960 - 2022' '1960 - 2022' '1960 - 2022'
 '1960 - 2022' '1965 - 2022' '1992 - 2022' '2007 - 2022' '1989 - 2022'
 '1981 - 2022' '1993 - 2022' '1960 - 2022' '1992 - 2022' '1993 - 2022'
 '1966 - 2022' '1960 - 2022' '1997 - 2022' '1967 - 2022' '1992 - 2022'
 '1986 - 2022' '1993 - 2022' '1992 - 2022' '1993 - 2022' '1973 - 2022'
 '1971 - 2022' '1960 - 2022' '1994 - 2022' '2006 - 2022' '1992 - 2022'
 '1960 - 2022' '1996 - 2022' '1991 - 2022' '2006 - 2022' '1992 - 2022'
 '2002 - 2022' '1995 - 2022' '1995 - 2022' '1975 - 2022' '1971 - 2022'
 '1962 - 2022' '2011 - 2022' '1962 - 2022' '1976 - 2022' '1986 - 2022'
 '1986 - 2022' '1964 - 2022' '2005 - 2022' '2000 - 2022' '1960 - 2022'
 '2005 - 2022' '1960 - 2022' '1960 - 2022' '1960 - 2022' '1968 - 2022'
 '1960 - 2022' '1960 - 2022' '1986 - 2022' '1988 - 2022' '1970 - 2022'
 '1981 - 2022' '1960 - 2022' '1960 - 2022' '1960 - 2022' '1981 - 2022'
 '1994 - 2022' '1960 - 2022' '1960 - 2022' '1960 - 2022' '1960 - 2022'
 '1960

In [131]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [132]:
print(X)

[['Sudan' 138.8 1.0]
 ['Zimbabwe' 104.7 2.0]
 ['Turkey' 72.3 3.0]
 ['Suriname' 52.4 4.0]
 ['Sri Lanka' 49.7 5.0]
 ['Haiti' 34.0 6.0]
 ['Ghana' 31.3 7.0]
 ['Moldova' 28.7 8.0]
 ['Sierra Leone' 27.2 9.0]
 ['Laos' 23.0 10.0]
 ['Malawi' 21.0 11.0]
 ['Ukraine' 20.2 12.0]
 ['Pakistan' 19.9 13.0]
 ['Lithuania' 19.7 14.0]
 ['Estonia' 19.4 15.0]
 ['Burundi' 18.8 16.0]
 ['Nigeria' 18.8 17.0]
 ['S.T.&Principe' 18.0 18.0]
 ['Rwanda' 17.7 19.0]
 ['Latvia' 17.3 20.0]
 ['Bulgaria' 15.3 21.0]
 ['Belarus' 15.2 22.0]
 ['Czechia' 15.1 23.0]
 ['Mongolia' 15.1 24.0]
 ['Hungary' 14.6 25.0]
 ['Poland' 14.4 26.0]
 ['Burkina Faso' 14.3 27.0]
 ['North Macedonia' 14.2 28.0]
 ['Bosnia & Herz.' 14.0 29.0]
 ['Azerbaijan' 13.9 30.0]
 ['Egypt' 13.9 31.0]
 ['Kyrgyzstan' 13.9 32.0]
 ['Romania' 13.8 33.0]
 ['Montenegro' 13.0 34.0]
 ['Slovakia' 12.8 35.0]
 ['Palau' 12.4 36.0]
 ['Serbia' 12.0 37.0]
 ['Georgia' 11.9 38.0]
 ['Botswana' 11.7 39.0]
 ['Chile' 11.6 40.0]
 ['Gambia' 11.5 41.0]
 ['Uzbekistan' 11.4 42.0]
 ['Samoa'

In [133]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [134]:
print(X)

[[0.0 0.0 0.0 ... 0.0 138.8 1.0]
 [0.0 0.0 0.0 ... 1.0 104.7 2.0]
 [0.0 0.0 0.0 ... 0.0 72.3 3.0]
 ...
 [0.0 0.0 0.0 ... 0.0 1.7 146.0]
 [0.0 0.0 0.0 ... 0.0 1.4 147.0]
 [0.0 0.0 0.0 ... 0.0 1.0 148.0]]


In [135]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [136]:
print(y)

[ 0 41  0  0  0  0  5 26 39 24 18 27  0 26 27  6  0 31  7 26 21 27 26 27
 13 11  0 28 38 26  0 30 25 38 26 35 29 29 15 11  2 42  2 16 21 21  4 37
 33  0 37  0  0  0  8  0  0 21 23 10 18  0  0  0 18 28  0  0  0  0  0  0
 14  0 20  0  5  7  0  0  0  0  0 22  0  0 32  0  0 28  0  0  0  0  0 26
  0  0  0  6  0  9  0 36  1  0 20  0  0 15  7 18 18 12 33 29  1 17  0  0
  0 17 21 40 10  0  6  3  0 10  4 18  6  0  0 30 21  0 34  0  0  4 21 22
 19  0 27 24]


In [137]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)


In [138]:
print(X_train)

[[0.0 0.0 0.0 ... 0.0 4.4 127.0]
 [0.0 0.0 0.0 ... 0.0 6.7 98.0]
 [0.0 0.0 0.0 ... 0.0 11.0 43.0]
 ...
 [0.0 0.0 0.0 ... 0.0 8.3 73.0]
 [0.0 0.0 0.0 ... 0.0 2.5 141.0]
 [0.0 0.0 0.0 ... 0.0 11.9 38.0]]


In [139]:
print(X_test)

[[0.0 0.0 0.0 ... 0.0 6.3 101.0]
 [0.0 0.0 0.0 ... 0.0 5.0 122.0]
 [0.0 0.0 0.0 ... 0.0 9.7 55.0]
 ...
 [0.0 0.0 0.0 ... 0.0 10.5 49.0]
 [0.0 0.0 0.0 ... 0.0 7.2 90.0]
 [0.0 0.0 0.0 ... 0.0 2.3 143.0]]


In [140]:
print(y_train)

[ 6  0  2 30 38  2 17  1 31 18  0  0 20  7  0 21  0 11 29  0 19  0 10  0
 40  0  0 27  4  6  0  0 22 18  0  5  0  0 28  0  7 21  4  0 33  0  0  0
 18 26 25 21 15 22 15 24 28 27  0 24  0 26 36 18  0 34  0 18  6  0 42  0
  0  0  5 16 13  0 12  3  0 27  0  0 27  0  0 20 37 29 26  0 39  0 18  0
 41 21 26  0  0 26 32  0  0 37  9 21 11  0  0 10  0  0  0 14  0 29]


In [141]:
print(y_test)

[ 0 17  8  1  6  0  0  0 21 10  0  0  0 27 23 38  0 26  0 35  0  0 30  4
  7 26  0 33 28 21]


In [142]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [143]:
print(X_train)

[[0.0 0.0 0.0 ... -0.0924500327042049 -0.4503704861693114
  1.167542539999475]
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.3185997337476307
  0.5065017438581443]
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.07224571835057537
  -0.7471963177892073]
 ...
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.22693312336733099
  -0.06336101143610642]
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.5592245859959173
  1.4866656829642555]
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.020683250011656808
  -0.8611688688480574]]


In [144]:
print(X_test)

[[0.0 0.0 0.0 ... -0.0924500327042049 -0.3415163863427056
  0.5748852744934544]
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.41599550727669904
  1.053569988940625]
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.1467248392845689
  -0.47366219524796693]
 ...
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.10089153409441902
  -0.610429256518587]
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.289953918003787
  0.32414566216398405]
 [0.0 0.0 0.0 ... -0.0924500327042049 -0.5706829122934548
  1.5322547033877956]]
